version: "2"
services:
  app:
    container_name: test
    restart: always
    build: .
    ports:
      - "4001:3000"
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017" 
    volumes:
    - mongodata:/data/db
        
volumes:
   mongodata:


# version: "2"
# services:
#   app:
#     container_name: test
#     restart: always
#     build: .
#     ports:
#       - "4000:3000"
#     links:
#       - mongo
#   mongo:
#     container_name: mongo
#     image: mongo
#     ports:
#       - "27017:27017"
